#!/bin/bash

apt-get update
apt-get -y install nginx

apt-get -y install mariadb-server

#mysql -u root -p > CREATE DATABASE wordpress_db; GRANT ALL ON wordpress_db.* TO 'wpuser'@'localhost' IDENTIFIED BY 'Passw0rd!' WITH GRANT OPTION; FLUSH PRIVILEGES;

mysql -u root -e "CREATE DATABASE wordpress_db;"
mysql -u root -e "GRANT ALL ON wordpress_db.* TO 'wpuser'@'localhost' IDENTIFIED BY 'Passw0rd!' WITH GRANT OPTION;"
mysql -u root -e "FLUSH PRIVILEGES;"


apt-get -y install php8.3
apt-get -y install php8.3-cli
apt-get -y install php8.3-fpm
apt-get -y install php8.3-mysql
apt-get -y install php8.3-json
apt-get -y install php8.3-opcache
apt-get -y install php8.3-mbstring
apt-get -y install php8.3-xml
apt-get -y install php8.3-gd
apt-get -y install php8.3-curl

mkdir -p /var/www/html/wordpress/public_html

cd /etc/nginx/sites-available
uri='$uri'
cat << EOF > wordpress.conf
server {
            listen 80;
            root /var/www/html/wordpress/public_html;
            index index.php index.html;
            server_name SUBDOMAIN.DOMAIN.TLD;

            access_log /var/log/nginx/SUBDOMAIN.access.log;
            error_log /var/log/nginx/SUBDOMAIN.error.log;

            location / {
                         try_files $uri $uri/ =404;
            }

            location ~ \.php$ {
                         include snippets/fastcgi-php.conf;
                         fastcgi_pass unix:/run/php/php8.3-fpm.sock;
            }

            location ~ /\.ht {
                         deny all;
            }

            location = /favicon.ico {
                         log_not_found off;
                         access_log off;
            }

            location = /robots.txt {
                         allow all;
                         log_not_found off;
                         access_log off;
           }

            location ~* \.(js|css|png|jpg|jpeg|gif|ico)$ {
                         expires max;
                         log_not_found off;
           }
}
EOF

cd /etc/nginx/sites-enabled
ln -s ../sites-available/wordpress.conf

rm /etc/nginx/sites-available/default

systemctl reload nginx

cd /var/www/html/wordpress/public_html
wget https://wordpress.org/latest.tar.gz
tar -zxvf latest.tar.gz
mv wordpress/* .
rm -rf wordpress

cd /var/www/html/wordpress/public_html
chown -R www-data:www-data *
chmod -R 755 *
mv wp-config-sample.php wp-config.php
table_prefix='$table_prefix'
cat << EOF > wp-config.php


<?php

define( 'DB_NAME', 'wordpress_db' );

define( 'DB_USER', 'wpuser' );

define( 'DB_PASSWORD', 'Passw0rd' );

define( 'DB_HOST', 'localhost' );

define( 'DB_CHARSET', 'utf8' );

define( 'DB_COLLATE', '' );


define( 'AUTH_KEY',         'put your unique phrase here' );
define( 'SECURE_AUTH_KEY',  'put your unique phrase here' );
define( 'LOGGED_IN_KEY',    'put your unique phrase here' );
define( 'NONCE_KEY',        'put your unique phrase here' );
define( 'AUTH_SALT',        'put your unique phrase here' );
define( 'SECURE_AUTH_SALT', 'put your unique phrase here' );
define( 'LOGGED_IN_SALT',   'put your unique phrase here' );
define( 'NONCE_SALT',       'put your unique phrase here' );

$table_prefix = 'wp_';

define( 'WP_DEBUG', false );

if ( ! defined( 'ABSPATH' ) ) {
        define( 'ABSPATH', __DIR__ . '/' );
}
require_once ABSPATH . 'wp-settings.php';
EOF
